# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190816_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeuser',
            old_name='user',
            new_name='Cakeuser',
        ),
    ]
