# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-16 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190816_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeuser',
            name='Cakeuser',
        ),
        migrations.DeleteModel(
            name='Cakeuser',
        ),
    ]
