# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190816_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
